[versions]
# Build & Core
agp = "9.0.1"
kotlin = "2.3.10"
composeBom = "2026.02.01"

# AndroidX
activityCompose = "1.12.4"
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.10.0"
window = "1.5.1"

# Network
apollo = "4.4.1"

# Storage
datastore = "1.2.0"
room = "2.8.4"

# DI & SDKs
koin = "4.1.1"
kotzilla = "2.0.6"

# Libraries
coil = "3.4.0"
coroutines = "1.10.2"
collectionsImmutable = "0.4.0"
lottie = "6.7.1"

# Testing
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
junitPlatformLauncher = "6.0.3"
junitPlatformEngine = "6.0.3"
journeysJunitEngine = "0.2.2"

# Analysis & Coverage
detekt = "1.23.8"
detektRulesKtlintWrapper = "2.0.0-alpha.2"
jacoco = "0.8.14"

[libraries]
# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
# noinspection UnusedVersionCatalogEntry
androidx-windows-windows = { group = "androidx.window", name = "window", version.ref = "window" }

# Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
# noinspection UnusedVersionCatalogEntry
androidx-compose-material-windows-size = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

# Kotlin & Coroutines
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "collectionsImmutable" }

# Network (Apollo)
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime" }
apollo-cache = { group = "com.apollographql.apollo", name = "apollo-normalized-cache", version.ref = "apollo" }

# DI (Koin & Kotzilla)
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-androidx-navigation = { module = "io.insert-koin:koin-androidx-navigation", version.ref = "koin" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-test-implementation = { module = "io.insert-koin:koin-test", version.ref = "koin" }
kotzilla-sdk = { group = "io.kotzilla", name = "kotzilla-sdk-compose", version.ref = "kotzilla" }

# Coil
io-coil-kt = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
io-coil-kt-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

# UI & Animation
com-airbnb-lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

# Storage (Room & DataStore)
# noinspection UnusedVersionCatalogEntry
androidx-room-compiler-database = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
# noinspection UnusedVersionCatalogEntry
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
# noinspection UnusedVersionCatalogEntry
androidx-room-runtime-database = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
# noinspection UnusedVersionCatalogEntry
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
# noinspection UnusedVersionCatalogEntry
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# Analysis & Code Quality
detekt-rules-ktlint-wrapper = { module = "dev.detekt:detekt-rules-ktlint-wrapper", version.ref = "detektRulesKtlintWrapper" }

# Testing
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
journeys-junit-engine = { group = "com.android.tools.journeys", name = "journeys-junit-engine", version.ref = "journeysJunitEngine" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-platform-engine = { group = "org.junit.platform", name = "junit-platform-engine", version.ref = "junitPlatformEngine" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatformLauncher" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
# noinspection UnusedVersionCatalogEntry
jacoco = { id = "org.jacoco", version.ref = "jacoco" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotzilla = { id = "io.kotzilla.kotzilla-plugin", version.ref = "kotzilla" }
# noinspection UnusedVersionCatalogEntry
room = { id = "androidx.room", version.ref = "room" }
